#
# At least gcc version 4.8.3 20140320 (prerelease) (Sourcery CodeBench Lite 2014.05-29)
# works to create a static binary that runs on android
#

all:
	$(CROSS_COMPILE)gcc -Wall -static -o kexec-wrap kexec-wrap.c
